### PR TITLE
style: fix typos and add lint rules to improve code legibility

### PR DESCRIPTION
**Pull request by nicobritos**
* Fix typos in comments and code.
* Add lint rules to improve code legibility.
* Reorganized methods to have a consistent order (ex: fields - getters -constructors - methods).
* Add dart code metrics to improve code maintainability.
* Add badges to README

### CODE REVIEW

**Comment by mcfugger** [comment]
This branch is [2 commits behind](https://github.com/nicobritos/dart_pusher_channels/compare/style...mcfugger:dart_pusher_channels:master). Please, have a look at that.

**Comment by mcfugger** [comment]
Actually it's now 3 commits behind. I've added bug fix when the ConnectionStatus.connected was added to the event stream every time the pusher error event occurred, now it's not set if the current connection status is ConnectionStatus.established.

**Comment by mcfugger** [comment]
I've seen the reorganization changes, looks good. But hope it will not affect on the logic. I've been testing the package whole day to identify bugs.

**Comment by mcfugger** [comment]
Sorry for such situation. I now have a recent project with pusher channels and it's a good chance to check everything for bugs.

**Comment by nicobritos** [comment]
@mcfugger no problem! I have to leave for some hours and I don't think I will be able to update this branch today, but will do tomorrow otherwise!

In any case, I think this branch should be thoroughly tested in order not to break existing functionality, albeit the only changes were typos/rearange code, but let's take this PR slowly.


> Sorry for such situation. I now have a recent project with pusher channels and it's a good chance to check everything for bugs.

Hey, no problem! Let's take it slowly. This already works 10 times better than the official plugin for Android/iOS

**Comment by mcfugger** [comment]
@nicobritos First of all, thank you very much for your help! I tremendously appreciate it. I know, you may want to kill me, but what if we close this PR and you open new branch from mcfugger:master and then do styling? It would be safer then merging possible breaks due to the conflicts. I promise to stop committing to `master` unless the new  styling PR is done.

Again, thank you very much!

**Pull request closed without merging**
